### ISSUE TITLE
mitigate unpkg.com outages by hosting dist on api.mapbox.com

### ISSUE THREAD

**Issue by neemanjabu** [mapbox/mapbox-sdk-js#349] opened 2019-12-24 06:03 UTC
https://unpkg.com/@mapbox/mapbox-sdk/umd/mapbox-sdk.min.js
responds with 
429 Too Many Requests

**Comment by andrewharvey** [comment] 2019-12-24 06:13
previously requested to be hosted on the mapbox cdn in #216. For the time being you'll need to host it yourself.

**Comment by neemanjabu** [comment] 2019-12-24 06:31
In case someone else has the same issue, you can do one of the following:
1. Download **mapbox-sdk.min.js** from https://cdn.jsdelivr.net/npm/@mapbox/mapbox-sdk@0.9.0/umd/mapbox-sdk.min.js and host it yourself
2. checkout the project and run prepublishOnly script
`npm run prepublishOnly`
in order to get **mapbox-sdk.min.js** in **umd** directory

**Comment by andrewharvey** [comment] 2020-05-24 05:39
closing as a duplicate of #216

**Closed by andrewharvey** 2020-05-24 05:39 UTC
