### ISSUE TITLE
HTTP 413 getStaticImage

### ISSUE THREAD

**Issue by JoeLeeWu** [mapbox/mapbox-sdk-js#344] opened 2019-11-29 07:19 UTC
HTTP 413 getStaticImage.
How to fix this problem?
Any ideas, thanks!

**Comment by joeyhub** [comment] 2019-11-29 16:30
If it's owner id try putting it in as mapbox.

**Comment by andrewharvey** [comment] 2020-01-26 03:25
@JoeLeeWu we'll need more information to work out what the issue is. Could you post a minimal code snippet that's causing this?

**Comment by andrewharvey** [comment] 2020-02-08 13:53
There's not enough information here to identify what the issues is so I'll close it. Feel free to come back if you have more details.

**Closed by andrewharvey** 2020-02-08 13:53 UTC
Labels: needs information

**Comment by fernandopg** [comment] 2022-03-17 11:14
Hi @andrewharvey, I am having this issue as well when the size of the URL is too long

And here is an example: https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/path-4+555-0.8(%7B%7DjgG%60p%60RRIRj@PHPDz@QRKLOh@%7DAb@eAXi@d@cAdAiBVk@H%5B@%5BCy@@YNUt@_@v@g@r@w@HYD%5B@YEYSAKRMNQFSEu@o@%7B@qAIWPQd@BnAIREB%5BQQi@AUCs@e@QQKYOUSMQ@QDu@ZWBg@%3FQGSmAAYPOh@Lh@%3F%7C@MzAw@RCTIROVURMVENMA%5BU%3Fg@JSAqA%5BQGFWf@%3Fb@KPSRKPE%60@UPC%60Be@tBId@Gd@Qx@e@PQTK%7C@Uf@Sf@It@Ux@Q%7EB%7DAbCsA%60@%5Dv@g@PITCPK%60@_@b@Qf@CRE%5E%5Bb@Qb@W%7C@aAfB%7BBp@o@p@w@d@%5BLNDZ%5BbAEZJRRKb@_AhAwA%5E%5DNSRM@%5CIt@Op@PL%7C@gAt@mA%5Ec@NSNGdDEz@NnA@THPGD_@%3FaBBs@A%5BMWc@g@%5Bi@IUGo@Dw@D%5D%60@kAXk@LWrAoAv@i@RGTATDrAJh@STGh@@RDTFPA%3F_@Yi@m@w@w@kASo@y@qESq@Mw@BYHWJUNSlAuANMRI%7E@YdAYVEj@%3FbAOV%3FbADr@NdAV%7C@j@VDj@OT%3FVDXLfAHjAEREHa@Mq@Sq@McAK_@m@mAK%5DCa@L%5BvB%5DrAm@XGP%3Ff@Hh@DZG%60@YhA%5BTS%5Es@NKTEh@HTCj@QTCTOF%5B%3FcAN%5BlAy@r@w@HYEYSo@k@%7B@w@s@Qk@%7B@gBK%5Ba@qAS_AE%7D@B_@F%5DZo@%5Eq@d@a@%7C@a@REh@@VCTKNUJW%3F%5DQmA%3F%5DH%5Db@mApBgEPK%60C%60@n@D%7E@Vj@Rl@Jn@Fl@GdAUn@Bl@%60@P%3FPYDa@BeAHgAMu@a@yAm@iAM_@UoAAaABc@%5C%7DBPm@HQRWVOPEV%3Ft@Nd@@t@CPKJUHYJo@%60@uD@Y%3Fc@M_BBuAFc@NYRWl@_@PYh@wAVeBL%5DN%5Bh@k@TOPCj@BNIR%5B),path-4+555-0.8(s%60dgG%7CsgQ%5BH_@FGFCHEh@m@%7CAYlAW%60Bi@nASl@Kf@%7D@nCCPGhACPINSVe@%5CMTITCP@VTjAB%5EG%5CKRUXIb@CdADh@%3FhAK%60@%5Dr@a@%60CAP@%60AGfBQp@g@t@EHIdACv@@JNP%5CJ%60@Bh@%3F%7CAEv@GrDi@z@I%60@MNIr@q@z@cA%5CUp@m@PGH%3FFBLNj@%7CAVh@h@l@ZVJLBRARy@nCu@tBoAlEO%5Cu@pAs@%60BMPMH_AIUBa@TaA%60AYd@Uh@Ql@a@xBa@lBGl@%3Fj@BP@f@Jb@RZx@p@BR%3FVCRUv@%3Fd@%5ElA%5Cx@Rz@HBDKu@MYCq@%5CgAVMHUVOZCNHZj@%7C@n@tAF%60@%3FPCLGJSJW%3F_@GIBo@VaAPIDKVGd@ARB%5EPdA%3Ff@Eb@K%5EIp@@%7CBAb@EJEHKDIBMCe@%5Dc@e@U_@ESU_@EWMOIS%5DqBSg@%5Be@OMmBcAE@GD%7DAvAQVGPMt@Gr@HtCB%60@NnADNNLFABILo@Pg@RWLEPARFTP%60AfA%5Cn@Vr@R%5Cn@p@%7E@nAl@j@%60B%7EB%5Ej@Vf@NJVBVEFETWVO%60@%3FVFNI%60@u@TgABg@KmAWyA%5BaAMm@%3Fk@BSBClAq@p@YFAN@%5CDXJNRFPXP%60@BVEXAf@LXn@DDNFHG@%5DNcABc@%3F_AMy@IQAIDOh@i@%5CIRCLDdAHb@MVAB@HHXv@R%5ET%7E@Hj@JVX%5EHVRPT%5EXBDM%5CoAD%7D@CyBBMPk@D%5DTq@j@u@TM%5CWZQ@@C%5Cs@%60BIf@Qb@UvA@n@LnAFV%5EdAFl@GtDKNCPDnADND%5ECFQIOAu@FSOSUS%5DUSIBGDKTMv@@h@G%7C@Ur@MPO%5ESv@KZUtASp@Cx@ThDA%60BOt@i@pBe@%60CGn@@vAm@vAGZQVYN_@HKAg@Qk@%5CMTGR%5CzD@l@CdAE%60@S%7E@Cx@%5CfC%3FPGZqAnCIZ@VNMb@i@TONUf@g@P%5BP%7B@BkBNmAl@sBLYb@c@%5CQb@IX@%5CFd@CLIb@o@%5EWp@QXAL@j@%5CJNJ%5EF%60@@VAvAo@bJMbA_BdEYb@%5DZ_@n@o@lCQV%7B@bA_BzBOHgBzAq@v@QJ_AAQBQP%5DvBKt@CJEFUD_BK%5DBIFg@j@OJaBXYJQXUh@SRKBWGUYMg@IgACKIGK%3FKF_Ax@IDIAGGEM%3FO@QPm@@KAMGGIEYFiDrBeCdA%5BVm@z@%7B@l@sCxBm@n@%7D@x@k@r@%7DB%7EDSf@Ol@Q%60BQfAGbAc@fLA%7C@DtAC%5EOVu@l@OZG%5EGbBGv@Ob@g@hAg@jBu@%7CBqBzEMj@E%7E@Il@%5DhAON%5EIVSNWh@yAd@w@NKxAs@p@Ob@@v@RfEtA%60@RLJJPFTDV@xDr@pI%5E%60DNfA@XGREHUPQB%5DK_Ai@MCk@Ia@%3Fe@Fe@PQJe@%5CQR%5Dn@Yt@sAvE%5D%7C@s@tAQXiA%7CAsCfDs@bAo@fA_ApBw@tBq@zBe@lBg@lCSbBQ%7CAYbEM%7C@Q%7E@Mf@Qd@c@v@_B%7EBa@%7E@UdA%5DpDWhAITWh@Yb@qAdBc@v@%5Bx@q@%7CBSh@Yd@%5D%5Ca@VQFc@Hy@%3FsBSiACw@Dc@Dc@Js@Tc@Ru@f@s@p@Y%5CiA%60BaBpCmBtDi@nAy@tBY%7E@%7B@jDgA%7EFc@jB%5BdAqAbD%5BbASjAe@zDGb@YfAa@%60AS%5CUXq@l@s@%5E%5BH%5DB%5BA%5DGYM%5BUU%5BS_@Oc@Ke@MsAOqEO%7BBSoAi@oBo@%7DAu@kA%7B@%7B@cA%5BWAU%3Fm@FSHQNORWr@YjAIPU%5CGN%3FPBNJDHAFGBKAMCIGEI%3FKDg@%60@%7DFjCa@HS%3FQCQIOQMSgAuCUwAGIK%3FGDEJE%5CQxFKnA%7D@lI%5B%7CAa@hA_B%7EBkAnA%7B@%5Eg@DS%3Fc@Ia@O_@YcBqBa@s@m@%7DA_@o@g@i@%5DS%5DK_@G_@%3FO@_@HaAd@uBzAm@T%5DBa@A_@MMG%5DYWa@%5B%7B@Kk@Q%7BAG%7DDCYOq@Wo@a@g@SMgAWW@YBWJWNi@h@wDdFk@h@o@Zm@L%7D@ByAMoASMBMFINCR%3FTFRHPLLjAz@%7CC%7CAf@d@r@%7E@r@%7CA%60EpKj@jAvAbCZv@Lh@Fp@V%60EXjCXhAhAbCPp@BZLjC%5EdLNfGCzAGbAe@jCCd@U%60BW%7C@_AtGaAbGiApFw@tEyB%60K%5DlAWl@MTiAxAYf@iBxEcAvC_@lAe@hCcA%7CGcA%7EIa@tAo@tA%5D%60AOfAChAPbA%7C@pDt@hC%60@hBJZPR%3FLFL%3FLDL%5EZbClCp@v@f@r@Zj@rC%7EFV%60@VPZD%7CAE%7C@Bp@B%60@Jn@X%5EZLPb@x@X%60@%7EEtF%5Ej@r@vAf@b@vBvAzAlAF@NEFCR%5DJ%3FB@JZVNVDT%3FXMPMb@m@V%7D@d@gAxBwDd@_AHg@%3FeBBOFMVOt@Y%5EYj@e@HMFUBq@GUCCk@ZS%3FWKQKU%5Ba@s@MOGWDMHGnBOHI@I%3FUKE%5B%3FSCo@%5Bq@cAOOa@CS@SFg@Ri@JIAMOWqA%3FOBMJC%5CFV%3Fn@Il@WPEj@Wp@Sn@a@VSPGHKBOAECA_@DEBc@BaAQMQ@MDGrA%5BpAs@bA%5Bz@Mv@@t@GdAe@v@i@v@%5BtFyA%60Ai@%60As@hAk@%7E@m@%5C%5BPGj@%5DXYjAy@%60Bi@%5EGTQLE%7C@y@j@w@h@c@%60AiAb@c@%5Cc@XUF@DR%5DtB@VJBLCb@o@PMb@o@Xi@p@s@FCJABB@LEP%5BlADNFDZQDGZWt@_A%5Cu@TULGXEh@%3Fv@CtAHh@GdA@NCDCHM%3FKAWe@uBo@oBKeA@y@F_@%5EmA%5Ew@NU%7CAmAh@i@LGf@A%5EFx@DXCz@%5DVGH%3Fh@PLG%3F%5BG%5BIUUa@UUe@u@O%5Dm@wC%7B@mCEk@Dm@L%5Bd@q@%7E@%7D@%5ESz@UbB%5Dh@Gr@STA%60ADr@Pt@HvAv@%60@@l@OTC%5EB%5EA%5EHT@p@%3F%5ECDE@K%3Fa@_@eAAe@EYYq@%5Da@Qg@AM@KB_@FINIhBMv@%5Bf@MXCpAHr@Uz@Il@%5Bf@k@TQHCt@%3F%7E@K%60@MFK@OBu@BOLc@NU%60Au@Za@Ti@@WOYgCmCQ%5Da@gAq@%7DDE%5D%3FkABg@HYd@iANSf@c@%5CO%5CGh@DR%3FPKVYFWD%5DG_B@%5BDYf@iBPYLOd@eAVo@RYPEf@H%5C@pAVpANpAT%5CD%5C%3Fr@Ef@Kh@%3FT@p@%5CJ%3FHCFIJi@HkA@a@A%5Dm@iB%7B@cBM_AF%7DBVcCNe@Pc@PWTOVIVAJ@%5EJXFl@A%5EIP%5BNs@d@qE@e@IqBAw@Bc@Lg@Rc@%7E@y@FK%5EkAf@_CXi@f@k@TQVEd@BJAJELWD_@D%7DAV%7DC@e@EQm@gAIWCWDm@l@%7DCZqBBm@Ai@Mq@M_@SSkAe@%7D@e@g@GyBPg@@_@EMGMKu@%7BBYmAe@kFSgDM%7D@%5BeBI_ATaLFk@P%7B@bAaCTa@l@%7B@p@m@XO%7C@Up@WXEV%3FVHn@XJ%3FLCHGR%5Bf@uBHMd@UJMDMBc@%3F%7B@_@wEQeH_@%7BIAo@FyAXuE%5CqD%5EwCPcCNiAA_@QoA%3Fw@GOGAQHWVUb@EXAb@Nr@@XGVKNIBGI@e@GWQ%5DSUKUa@iBF%5D%7C@%7DB%3FEIO%5Ba@%7DAcB%5De@WQ_@DeA%5CK@%5BC%7BEuBg@k@MIOAo@@MEoAg@e@ISAg@BUDk@Pg@%5Ca@j@OX%5Bv@yA%7CE%5D%7C@a@z@c@t@w@hAcCtCcAtAoAxBeAbCg@rAo@xB%5D%7EAe@%7EB%5DvCk@vGSnAQt@Up@%5Dl@eBdC%5Bp@K%5CSjA%5DbDYnAe@bAyAlBg@x@a@bAm@vBWn@MRORc@%60@_A%5Cm@BiCU%7BACaBN%7D@Xa@Pm@%5Ek@f@oA%7CAy@nAaChE%7BB%7CEq@fB%5BfAs@rCgAjGYjA%5BfAsAjD%5DdAUjAe@%7EDUjAe@tA%5Dl@WZq@n@%5DP%5DJ%5DF_@%3F%5DE%5DM%5BUW%5BSa@Qc@Kg@MuAOsEIqAOmAa@kBm@cBu@wASWi@m@WQWKWIs@GY@WBUJUNQTKX%5BtAIVMRm@p@OJu@%5EoAr@mBz@SFa@Fa@ESKSUOWo@oBSu@WiBw@kEKeAOoCAeBIc@Uy@Im@AYDs@j@aCHs@%3Fw@EYQq@Wq@_@k@SOUKWEs@EqCKQCOIOOISGUEs@CwBMwHAcAFiCh@gGNo@LOLMPEdAB%7CAMPELIFM@SCUi@wAMu@C%5BA%5D@%7D@D%7D@NkALm@%5Cy@NiBZaBTk@v@oARm@Hq@LaCTwAPs@P%5D%5Ek@Xm@%7E@%7DATg@%5Ei@Z_AJo@h@iAX%7D@Lu@Hy@B%7D@A%7DCJcAFSTa@vAuB%7E@qBXc@l@q@%5CY%5CQtAg@h@%5DX%5DTc@Pi@Lk@n@sGZyE%60@mIDaB%3FiAEkAGo@o@_EiAqGIo@%3Fs@Hs@FWXi@%60@a@hBmAZ_@Te@Ji@BaAC%7B@SeC%3Fq@Do@Hi@HWZq@NSXUFCT@p@TnAv@r@h@v@%7C@j@%7E@%5Ez@F%60@B%60@CR%3Fh@I%60C@%7EACt@DTVfAt@rBPn@Fh@Gx@@ZNNJ%3Ft@g@N%3FJH%3FNAH_@%7E@MhA%3Fl@@%5EH%60@Tb@%5E%5ERJ%5EFdAJT%3FXGNIj@w@XOh@Mx@GXBf@NF%3Fp@Eh@Af@Hh@TPFH%3FNCVWFUBYCWIS%7B@wAm@u@K_@@WL_@Vc@%7E@_ANINENDTNHLBTCFEDm@DULIRCRBf@NTZNN%3F%5CEN@FBh@z@Ph@l@%7ECl@lBBTIn@O%5COHkAES@%5BFk@POHWVWd@WV%5BH%7B@FGBQLKTGXCZ%3Ft@Bf@%5EbB@XEVSXYNg@HmAAQFON_@p@Sj@%5D%7EAIr@%3F%7E@FVJRFDPDf@M%60@EH%3FTF%5ETp@l@PTLZDf@GhC@h@LXXTJLLZD%5EIx@y@%7ECEVBVJFFCFMVkAb@oALe@RsAJcCNyAJa@HUZa@N%5D@YAUi@aBA%5DFYRc@d@o@Xm@Jg@LuALe@j@eATWHE%5E@FH%3FLEP_@TMNITOhAIlAUjBAVDVRv@%5E%60AFV@v@GbBg@lBSrAIhAO%7ECIbA@LFVDFH@FCFGFUVwDFi@Nu@r@eCv@%7DALc@BYCs@@q@JiARiATw@Vg@%5E_@%5EWPGd@KbACl@EP@FFFRAHCFGBg@Co@I%5B@%5DJQLORKTMf@Gf@KxCKdEArABjBRnDBJNNH%3FFCJSBYEaB%3FaAH%7DAJaAZeBfAgEJUFIFEH@FDBLAJg@jAOp@QxAClANvB%5CbCj@vCP%5EDFFBPCDGFW%3Fe@M_C%3F_AJ%7DBHo@Rw@Ri@%60@%7B@h@u@%7EBkCpBkBHGVIVC%60@%3FzAJlAPn@%3F%5EAtAR%5C@z@IdAF),path-4+555-0.8(aadgGnrgQNP@R_@Tc@HOH%3FTBVO%5C_@h@Sf@Sx@Ef@GTcAtCy@%7CCWv@Gh@Ad@GNY%5Ck@%60@O%60@Cf@@Tb@xAALMZa@%60@FLMXBr@Ah@B%7CAAf@KLSNGLK%60A@RY%7EBBvACZCNMZY%60@SZEPCR%3Fv@Gd@%3FNFNZLZFZ%3F%60BGfAKrDi@jAGd@Oj@_@ZWNWN%5BRW%60Aq@RSLCJBHHf@%60BNZn@%7E@f@j@DLAPSh@Oz@EFi@pBg@vAc@dBc@jAi@fA_@bASl@g@f@q@Iu@Hm@h@i@t@_@v@W%7C@c@pBa@dBGp@C%7EADf@NZr@%60@VVBh@Ob@Kj@Jf@j@pARl@%3F%7C@_@Xa@EwBTm@@WTI%5CJ%5ELZfAdBNZJ%60@Q%60@WPYBWK%5B%3Fu@R%5DB%5DJS%60@Eh@Bj@VjAFd@Ef@K%60@Gf@%3Fh@Df@%3F%60@Ch@Ih@WV%5DAg@aASm@%7B@oBo@mCc@_Ao@i@k@a@c@Wa@Pu@r@UVYh@MnAKb@Ad@@%7EAFn@ZjBLTJDP%5BFs@F%5DNUHIRKH@%60@AAJd@f@XTJVNRx@hBZ%5C%5ERPT%5En@RPNZ%60@b@LDRRl@x@h@d@BJJJHLPh@HBVCTSNSf@a@%5EBVFLCRc@CO@SIs@%3FOOiAQ%7B@O_@YaAGa@C%5BDM%3FKDG%7E@o@%60Ak@JMh@Q%5CJVBXHPTFN%3FHFHN@bAOL@h@Pr@h@LDJADAD%5BEKAq@I%5Dg@oAAMBKHIDSXc@FWTWnAAt@D%5EELG%5CRDN%5Cd@%5C%60ABXHd@LJN%5EJBXZLDBTHFLVDACEAQF%5DAq@Fg@JSCS@QHq@%3F%5DLSDOV_@Nu@Vg@t@%7B@JGFJALELMLa@j@Ql@Cz@Up@MHAR%3Fx@R%7CA@NCNH%60@PXBNBp@CP%3FzB%3F%5CCPFVFt@Jf@SEGE%5DAYGYSOa@k@%5BIBSXI%60@Cr@Kt@DdACNKLQh@Yf@DR%3FI@FMD@JIZGHCNSn@JREPDT%3FLSt@C%7C@HdAJx@@b@%5B%7C@K%7C@U%60ACb@G%60@%5D%60BGl@BbAKFM%3FQNOp@A%5CK%5EOH%5B%3FOEG@UEu@EWP%5Dx@JdAH%5ER%7CB%3FNI%60AM%7E@IxBBv@Lf@@REPPD%3FNKJQb@MFBRYj@IN%5BXO%5CBJREf@k@%5CY%5Es@XOV%5DJUEo@B_AVkBJO@OJGJQ%3FSFSF_@DKRYTSf@MXAr@DXEVQZm@XWv@Kb@%3FVFHH%5C%60@Np@%3Fr@%5DfGSdDKv@gAxCYr@UXe@%60@%5Bh@iAhFQfC),path-4+555-0.8(acegGx%7DkQIb@GnALzB%60@xB),path-4+555-0.8(uncgGbrlQO%60@CRAfAI%60AId@AV%5B%60BEx@e@tCDV%3FZHp@HV%3FFJn@APE%5CQh@e@%60DMb@%3FTMd@SnBDTAVMZ_@XINKPG%60@KVINQPKDW@SK%5DGACq@EKDSNKNKVAZ@ZZtBLdABJ@PAt@C%5CMn@%3F%5E%3Fn@BR%3Fj@JpAANG%5EWd@Md@o@jACPBLD@DELa@PUNO%5Co@d@c@Le@Bi@Au@@%5DHg@j@mBXw@Ve@b@_@XIXChAFNCXUXc@TUPITGj@EH@f@TRZJb@Fd@%3F%7E@IhBm@bIYhAiAtCW%5Em@j@MTKZa@jBQb@),path-4+555-0.8(knegGngsQqAi@%7B@Ia@@c@Jc@Pc@Z_@f@%5Bl@Yv@gAtD%5B%7C@q@xAc@r@g@n@oDbEs@hA%7BAzC%7BAzDUv@%7D@nD%7D@pGg@bGM%60AW%7E@m@lAeBdCYj@Up@GZa@xDMp@Qj@_@z@gB%60Ci@fAa@jAg@pBQ%60@q@v@k@Z_@Ja@Bc@AaAKu@Ca@Gs@Dq@Dq@JgA%5Ec@Tw@h@u@t@a@h@aBfC_CfE%7D@jB%7B@tBY%7C@g@%60BWfAUhAaApFWfAm@dBgA%7EB%5D%60AShAm@nFYnAe@dAW%5Es@t@%7B@d@_@H_@B%5DA%5BI%5DOYWS%5DQa@YkAKqAU_G%5DgC_@%7BAq@_Bk@aA_@e@_@_@c@WSIi@Gm@%3FWDUHUPOVKVi@hBGLUPi@j@gF%7CBu@Rc@CQGQKMOMSw@_CQo@Ks@CGECG%3FGBEFEVE%7C@IxCOxBu@bHS%60BS%7E@M%5Ec@t@%7BBxCQPe@Xe@Ng@@S%3FOCs@U%5DWmB%7DBc@y@c@mAYg@_@e@WSe@Ug@IY%3F%5BBYH%5BLe@VoBvAu@X%5BBK%3F%5BC%5BIe@%5Dc@y@Uq@Ic@Is@G%7D@),path-4+555-0.8(okjgGpz_RJSH_@@%5BGQGCKC_@RM@YI%5DWOOOg@S_@EQAKBKb@IFE%5CGJO@Qi@OSMUS%5Dw@SMWKYCY@o@%3FUNIAMOOs@CMDKRAV@r@_@tAi@XS),path-4+555-0.8(%7BvegGdmzQ%7E@F%60@%3FbB%5B%60@APBb@VNDL%3FLMH_@RiBAe@a@kBQe@g@eAMm@C%5DA%7DAFwAJ%7B@F%5DXu@PSPITEV@%60ARr@@%5EGNUPe@Lm@%5EwD@s@KiCBw@Je@HUP%5Bt@q@P%5DZ_A%5CsBPc@LU%5Ee@XSRG%5C@NANKJQFUJeC),path-4+555-0.8(qhfgGpprQTEbBBTAXOVYJSj@eB%5Ck@nBcAhAMp@L%60Bj@%7EAd@h@TTLNRHTB%60@A%7EA@dAr@%7EHVbCVxBB%60@E%5COTS@UC),path-4+555-0.8(guhgGl%60qQJb@h@bATbABXALQj@%3FTBHFFNCr@e@HCHBJLC%60@Wf@G%5ECb@%3Fx@Dj@DVLVNPRNl@VlAJ%5C@ZM%5C%5DTSVKj@E%7E@Qd@J%5ERV@f@Gb@@VEb@L%5CPRBH%3FHEJSFk@C%5BUi@q@o@y@_B%3FMBOPYjAyATW%5CGZLFDBJ%3FVEFQDSAO@KJIRAZFXLTZLbABTVZh@JPXlAC%60@B%5Ct@%7EAPt@Bv@CNWb@MBqAUg@Do@RKFWVg@t@KHe@PY%3FYAWNIPMh@El@@R%3F%7C@TfABb@Ad@IZSRKDw@LaAAKBUPSXWh@i@jBEn@Ap@B%5EJ%5ETRL@ZCd@QVALDd@%5CXXb@n@Nb@BN%3Fn@Q%7CA@j@Tb@l@h@FVB%5CCj@U%7E@%5D%60AIf@ALFXFFJ@HEHKBOHaALk@Xg@J_@LyB@%7DBD%5BPu@Xs@l@i@JM%3FGWk@YeACQAQB%5DLYn@aARe@Hi@FqARy@NYl@w@XKL@FJBLAJEJID_@HIBKVBpAIj@a@zBEv@Lh@d@%7E@LZH%5EHdBCXYzA%5DlAE%5CMxBOlAAp@KtABNDLHFJ%3FFIBMJuCH%7D@F_@x@%7DCjAuCD_@CqAFkAj@_CJY%60@o@ZYf@W%60@Gd@Ab@@j@CJBH@FHBJAJEFWHkAQi@@QJQRUh@Ip@GvBKnAIpDA%60BDvCDn@J%7C@HHHDJAHGDK@OI%7B@%3F%7DAHkBT%7BAd@cCZ%7D@Ru@Xs@PMHBDFDLI%5C_@l@W%60AKdAAz@@h@Dj@VrBb@nC%5C%7CAFJPNH%3FFEHYC%5DW_CAaAFiBRyAbAyBnAaBpDmDh@e@%5EO%5EI%7CBJ),pin-s-a+888(-3.120808,43.315022),pin-s-b+888(-2.993422,43.279621),pin-s-c+888(-2.9931937,43.27969313),pin-s-d+888(-3.015481,43.285137),pin-s-e+888(-3.018739,43.276756),pin-s-f+888(-3.052873,43.286942),pin-s-g+888(-3.117361,43.312082),pin-s-h+888(-3.089625,43.288301),pin-s-i+888(-3.049206,43.291139),pin-s-j+888(-3.041503,43.303408),path-2+555-1(o%7BjgGrq%60RuBYGAo%5EmWeMcREMe@yAwAsF%7D@qDQcAlCsfEBSlkBw_GZq@v%7DCarG%60AoANPnXbdCoBhrAo@bJgk@h%7BHqR%7Cx@u%5Dpn@GJax@%60aActAxpASJ)/auto/400x400?access_token=<ACCESS_TOKEN>

We saw that for other API requests there is a POST version. Is there a POST version for this request (Static Version)?

**Comment by micalevisk** [comment] 2022-07-08 19:51
@fernandopg  the docs has no reference on that https://docs.mapbox.com/api/maps/static-images
