### ISSUE TITLE
RequestError: getaddrinfo ENOTFOUND api.mapbox.com api.mapbox.com:443

### ISSUE THREAD

**Issue by RemiBardon** [mapbox/mapbox-sdk-js#261] opened 2018-07-18 14:27 UTC
Hi, I'm starting to use Mapbox API with Firebase Functions, and this error appears in my Functions logs 😕
I'm trying to solve my problem with [the documentation](https://www.mapbox.com/api-documentation/?language=JavaScript#insert-or-update-a-feature), but I didn't find how to fix it 😕
I'm trying to insert a new feature, and I think it's the problem, I didn't do this : "If you are inserting a feature, you must add the feature as the body of the PUT request."
I searched how to make a PUT request, but I don't find any simple solution 🤔 How do you usually make them ? It's weird cause it's never mentioned in the API documentation, I don't think it's the reason of my error 😕

Note: I'm using Node.js last version and my token allows DATASETS:READ, DATASETS:LIST and DATASETS:WRITE.

My code (basically the documentation):
```javascript
// …

const mbxDatasets = require('@mapbox/mapbox-sdk/services/datasets');
const datasetsClient = mbxDatasets({ accessToken: '*****' });

// …

// Adds a spot to a Mapbox Dataset
exports.addSpot = functions.https.onCall((data, context) => {
  datasetsClient
    .putFeature({
      datasetId: '*****',
      featureId: 'null-island',
      feature: {
        "type": "Feature",
        "properties": { "name": "Null Island" },
        "geometry": {
          "type": "Point",
          "coordinates": [0, 0]
        }
      }
    })
    .send()
    .then(response => {
      const feature = response.body;
    });
});
```

Thanks for your reply.

**Comment by davidtheclark** [comment] 2018-07-18 20:45
Hi @RemiBardon. `datasetsClient.putFeature` [is already making](https://github.com/mapbox/mapbox-sdk-js/blob/a3fd56b3369c5883f38b9b2cf969715fb9e06119/services/datasets.js#L163-L183) a `PUT` request for you.

I bet this is a repeat of the problem in https://github.com/mapbox/mapbox-sdk-js/issues/134

@RemiBardon how many requests are you making — just one? Or enough that you might be running up against rate limits?

**Comment by RemiBardon** [comment] 2018-07-18 21:48
That's what I thought for the PUT request, but it says you have to do something else if you are inserting a new feature, so it could be the error 💁🏻‍♂️
I already saw the problem in #134 , but the solution does not fix mine, since I'm making only one request…

**Comment by davidtheclark** [comment] 2018-07-18 22:10
@RemiBardon I'm unable to reproduce. Guess is that there's some kind of DNS lookup failure. Are you behind a proxy or in some other situation that would make your DNS lookup different?

Is this 100% consistent for you?

It would be helpful to see if you reproduce the error using the HTTP API directly (instead of through this SDK).

**Comment by RemiBardon** [comment] 2018-07-18 22:47
I’m not behind a proxy (as far as I can tell), and it happens every time I try to execute the Function.
I’ll try to use the HTTP API directly, but I won’t have plenty of time during the next days 😕 I’ll try as soon as I can 😉

**Comment by RemiBardon** [comment] 2018-07-18 23:16
If you think it's the error, you can close the issue 👍🏻

**Comment by davidtheclark** [comment] 2018-07-18 23:38
@RemiBardon Thanks for the details! Yeah, looks like this is about your Firebase account, not the Mapbox API or your Mapbox account. So I'll close the issue 👍

**Closed by davidtheclark** 2018-07-18 23:38 UTC
